### ISSUE TITLE
right-rails breaks jrs generator (js.rjs files render the erb code)

### ISSUE THREAD

**Issue by bidaian** [kaievns/right-rails#13]
Hi,

I tried the very simple ajax test application from[1] and it worked ok with a new application.  Then I installed right-rails (script/generate, adding the gem to environment.rb and the rightjs_scripts, restarting the server) and it stopped working!

It seems that the rjs generator never kicks in, I checked the return of the ajax call with foxhttp and I can see the erb code:

replace_html("current_time",{partial:"time/current"});

instead of the javascript code.

I'm running rails 2.3.5.  Any idea on what could be wrong?  Changing the filename to .js.rjs doesn't work either.

[1] http://blog.devauld.ca/2007/09/10/simple-rjs-example/

**Comment by bidaian** [comment]
Writing:

page[:current_time].innerHTML=render(:partial=>'time/current')

instead of:

page.replace_html 'current_time', :partial=>'time/current'

Works!  Maybe you could add a comment somewhere in [1] saying that the new javascript generator is not compatible with the old one?  I think I was misled by the "drop in replacement for all the Prototype/Scriptaculous methods".

By the way, it looks great, thanks!

[1] http://github.com/MadRabbit/right-rails#readme

**Comment by kaievns** [comment]
Hey man, yes the idea was to completely replace the original RJS generator, it replaces the old methods for various form elements and options like draggables, link_to_function and so one. but there are no the old things like `replace_html`, because we use free-scripting and that will pollute the name scope.

But I think you made your point. I probably could add some option to emulate those methods too.

And one more. Don't use direct `innerHTML` assignment, it won't work in RightJS2 like that. Check this out http://st-on-it.blogspot.com/2010/08/prepare-your-project-for-rightjs-2.html

**Comment by bidaian** [comment]
Good, thanks for pointing that out!  I'll take care of it.

**Comment by kaievns** [comment]
No problem. Keep me posted!

And I'll take care of the ticket on the next week

**Comment by kaievns** [comment]
i suppose as prototype features were kicked out of rails a while ago, there is no reason in keeping backwards comparability with it
