### ISSUE TITLE
Feature request: link_to_dialog helper

### ISSUE THREAD

**Issue by amdest** [kaievns/right-rails#22]
Hi, Nik.

Are you ever planned to implement this?

**Comment by kaievns** [comment]
no, not really, i'm happy with the form extensions, the rest of the things seems a bit of pointless coz in most cases people write custom helpers anyways and they fit better than some half-cooked generic helpers.

That's basically why the prototype helpers were kicked out of Rails 3, they just make you write shit instead of writing everything decently with say UJS

**Comment by amdest** [comment]
OK, got it.
