### ISSUE TITLE
RR.update_flash remove remove the #flashes div

### ISSUE THREAD

**Issue by Electron-libre** [kaievns/right-rails#6]
Hi mate,
Just found this issue, unless i misundertstand the use of RR.update_flash
But here is my investigations :
RR.update_flash call RR.replace on the RR.options.flashesId element with the content argument. But replace replace the element, not it's content.
I'll provide a fix soon, using the Element.update mehod instead.

**Comment by kaievns** [comment]
Hey man,

It uses the `replace` method because it hooked up to the `flashes` helper which normally generates the whole thing.

And as it's a whole thing it's better to simply reuse it and replace the whole block.

If you handle your flashes differently in your application it's easy to simple replace this method locally in your application and make it do what you need.

**Comment by Electron-libre** [comment]
Damned this is why ... :)
Of course I do not use the flashes helper. Indeed I use a steady flash element.
I'll give a try with the helper.

**Comment by kaievns** [comment]
btw: right-rails has the helper by default, just call it like `<%= flashes %>` and it will generate you a proper flash block with all the classes and IDs in place.
